spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: tech
  datasource:
    url: jdbc:postgresql://localhost:5432/techdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}
  security:
    user:
      name: admin
      password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
