spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: tech
  datasource:
    url: jdbc:postgresql://localhost:5432/techdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:ChangeThisSecretKeyForJwtTokenGeneration1234567890}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

server:
  port: 8081
